### ISSUE TITLE
Custom C# Hammer Helpers

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#2632] opened 2022-12-03 06:00 UTC
### For?

Hammer

### What can't you do?

We can't make custom entity helpers for hammer

### How would you like it to work?

We should be able to write custom helpers in C#
The existing helpers should also be remade in C#

### What have you tried?

Currently we have to play with the few hard-coded helpers like the door helper. They work in some situations but are a bit of a hack. They don't work for anything more complex like a multi-floor elevator.

### Additional context

Example of a hammer helper (DoorHelper)
![image](https://user-images.githubusercontent.com/39461072/205426974-ba93be8c-5ce3-4c55-a217-58296ef640bb.png)

**Comment by Adesii** [comment] 2022-12-03 06:05
dupe of #2607

**Comment by gvarados1** [comment] 2022-12-03 06:12
> dupe of #2607

whoops! I thought there already was one but nothing appeared when I searched "helper", needed to actually search "helpers"

**Closed** 2022-12-03 06:13 UTC
Labels: feature
