### ISSUE TITLE
[Prefab] attributes are not populated (at least for entities prefabs) when not set as [Net]

### ISSUE THREAD

**Issue by Guema** [sboxgame/issues#3099] opened 2023-04-05 16:01 UTC
So basically, tittle is quite self-explanatory, i wanted to be sure it was tracked somewhere, and i quickly checked if i was not going to create a duplicate, seems not (I hope, otherwise, sorry)

![image](https://user-images.githubusercontent.com/8943532/230133469-7099aa3e-dd98-4201-8cff-809589d45964.png)

This is based on Devultj code for a sample he made for FPS Sample.

I wanted to have Viewmodel animation parameters entirely client-sided, as it is for me purely cosmetics and only viewed on the client cam. So i just tried to remove [Net] from the attributes for the viewmodel, Problem is : the prefabs instances values of seems to be zeroed out when it is not [Net]ted.

I also get a 
![image](https://user-images.githubusercontent.com/8943532/230135815-33da74c5-3f15-44eb-82e0-3c020c105aac.png)
When i remove [Net] attribute.

However, exact same code, but with [Net] before each [Prefab] no longer throw an error and work perfectly as intended...
Problem is, those values have no sense to be networked from my POV.

I'm quite a novice in S&box api, so i could have missed something but i'm trying to have Prefabs that store client-sided datas (like a database), that doesn't require constant Server-Client validation, is this possible atm ?

i'm posting here after talking a bit about that in the discord : 

- I'm not really sure it's not intended
- Not really sure how it should work (Should it be populated at game loading ? server loading ?)

**Comment by DevulTj** [comment] 2023-04-10 23:37
This is currently as intended. 

The prefab is serverside, and we don't deserialize on both sides because we assume the properties would be sent to the client by the server (only if they need to be sent)

In an example where the viewmodel is an entirely clientside construct - it should be its own clientside prefab entirely - that or we implement something like "client only" components/prefabs on a prefab. This feature is on the original discussion https://github.com/orgs/sboxgame/discussions/2857 so I'm gonna close this issue and direct any further suggestions and feedback there.

**Closed by DevulTj** 2023-04-10 23:37 UTC
