### ISSUE TITLE
In game resolution cannot go past 1600x900 on a 2560x1440 display

### ISSUE THREAD

**Issue by deathchirps** [sboxgame/issues#2853] opened 2023-02-02 11:37 UTC
### Describe the bug

When navigating to settings tab and going to video, the resolution options go from 1280x720 to 1600x900 even though my display is a 2560x1440.

### To Reproduce

I haven't seen many other people with this issue, maybe just a handful while asking around.

### Expected behavior

The game should list my resolution.

### Media/Files

![image](https://user-images.githubusercontent.com/124260685/216314453-c24eb874-1a79-4f11-a65e-821a02568a4f.png)

### Additional context

Specs: 
CPU

	Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz

	Base speed:	3.70 GHz
	Sockets:	1
	Cores:	10
	Logical processors:	20
	Virtualization:	Enabled
	L1 cache:	640 KB
	L2 cache:	2.5 MB
	L3 cache:	20.0 MB

Memory

	128 GB

	Speed:	3200 MHz
	Slots used:	4 of 4
	Form factor:	DIMM
	Hardware reserved:	80.7 MB

Disk 0 (C:)

	Samsung SSD 970 EVO Plus 2TB

	Capacity:	1.8 TB
	Formatted:	1.8 TB
	System disk:	Yes
	Page file:	Yes
	Type:	SSD

GPU 0

	NVIDIA GeForce RTX 3080

	Driver version:	31.0.15.2756
	Driver date:	12/5/2022
	DirectX version:	12 (FL 12.1)
	Physical location:	PCI bus 1, device 0, function 0

**Comment by handsomematt** [comment] 2023-02-02 11:58
Do you have DPI scaling enabled through Windows?

**Comment by deathchirps** [comment] 2023-02-02 12:06
I just turned it off and I'm still having the issue

**Comment by robotboy655** [comment] 2023-02-02 14:33
Duplicate of https://github.com/sboxgame/issues/issues/2769

**Closed by robotboy655** 2023-02-02 14:33 UTC
Labels: bug
