### ISSUE TITLE
File edits in Visual Studio don't trigger recompiles if project files are on a different drive

### ISSUE THREAD

**Issue by Phyremaster** [sboxgame/issues#3875] opened 2023-08-19 05:48 UTC
### Describe the bug

Modifying and saving a file belonging to the active game or an enabled library in Visual Studio does not cause the game or library to recompile. Creating or deleting a file does trigger a recompile. Editing a file in any other editor does as well.

### To Reproduce

1. Create a project stored on a separate drive from Visual Studio and s&box.
2. Open the project in the editor.
3. Open its solution.
4. Edit and save an existing file in Visual Studio.

### Expected behavior

The project should be recompiled upon modifying and saving a file in Visual Studio regardless of where the project is stored relative to Visual Studio and s&box.

### Additional context

This bug is not perfectly consistent, but seems to be more consistent the further apart the drive technologies storing the files and programs are (i.e. it seems most consistent with files on an HDD while the programs are on an NVMe SSD). I am not certain whether it is the location of Visual Studio, s&box, or both that causes this issue. I've even heard some reports of it happening with everything on the same drive.

**Comment by handsomematt** [comment] 2023-08-19 09:29
It's likely Visual Studio's atomic saves that differ from how other editors save files, odd that it's not working for you though.

Is there anything specific to your setup, are your project files on a different drive, is it a HDD vs an SDD, if so what happens if you have them on your C drive?

**Comment by Phyremaster** [comment] 2023-08-19 15:10
As of my most recent reinstall, both s&box and Visual Studio are on my C drive, an NVMe SSD. However, upon double-checking this, I've realized that my Documents folder is actually on my D drive. Since s&box now stores projects in the Documents folder, the project files are on my D drive.

**Comment by handsomematt** [comment] 2023-08-19 15:12
You can store them wherever you want, try somewhere on your C drive perhaps. Is your D drive a HDD?

**Comment by Phyremaster** [comment] 2023-08-19 16:32
My D drive is a HDD, I meant to mention that in my previous comment.

I moved my default project folder and existing projects onto my C drive, and now saving modifications in Visual Studio does trigger a recompile. Thank you for your help.

While we have reached a sort of solution, I'd still consider this issue a bug, as ideally the location of project files should be irrelevant. I'll edit the issue title to be more accurate.

**Comment by Phyremaster** [comment] 2023-08-19 16:37
It's worth noting that this wasn't an issue for me until a few days ago, and I know that it wasn't caused by a Visual Studio update as my Visual Studio installer was bugged and unable to do anything at that time. This implies that the only change was a s&box update, so hopefully this can be fixed by reverting some small change.

**Comment by Phyremaster** [comment] 2023-08-24 08:44
Worth mentioning that I'm on Windows 10 and my project files were stored on an HDD while everything else was on an (NVMe) SSD. I'll edit better details into the issue before I forget.

**Comment by handsomematt** [comment] 2023-08-24 09:07
It does sound specific to HDDs doesn't it.

**Comment by dch-GH** [comment] 2023-08-24 16:55
My game is also on an SDD while my project files are on an HDD. Never had an issue

**Comment by Phyremaster** [comment] 2023-08-24 23:33
Yeah, it doesn't seem to be a very consistent issue with different users/computers. I will gladly provide logs, system information, directory trees, etc. if there's anything that might help narrow down what makes the difference.

**Comment by xezno** [comment] 2023-09-01 13:35
Duplicate of #262

**Closed by xezno** 2023-09-01 13:35 UTC
Labels: bug
