### ISSUE TITLE
I can't change the language

### ISSUE THREAD

**Issue by Urchik1982** [sboxgame/issues#3945] opened 2023-08-31 15:25 UTC
### Describe the bug

I can't change the language

### To Reproduce

1. Go to the settings
2. Pressed "Game"
3. In the "Game Language" window, I select any language
4. The language does not change and nothing is written in the console

### Expected behavior

**Change** the language

### Media/Files

https://github.com/sboxgame/issues/assets/143731773/4e14b572-98ef-429b-94fc-b2e77cae09f0

### Additional context

Running the game on Windows 11.
**_If you can help me, please write under this post._**

**Comment by xezno** [comment] 2023-09-01 12:58
duplicate of #3891

**Closed by xezno** 2023-09-01 12:58 UTC
Labels: bug
