### ISSUE TITLE
Metadata: s@box <-> asset.party

### ISSUE THREAD

**Issue by drednorzt** [sboxgame/issues#3209] opened 2023-04-27 20:45 UTC
### For?

S&Box

### What can't you do?

Synchronize user specified asset metadata (title, summary, description, tags etc) from asset.party back to s@box.

### How would you like it to work?

If I edit an assets details on asset.party, it would be neat if those changes were reflected back in s@box the next time I go to publish it. Currently S@box only remembers the previously input info pc-side, and so any changes made from the asset-party side get lost, unless you make a note of them first, to put back in again later.

### What have you tried?

Copying the details on asset.party into a temporary text document & adding them back in again manually.

NOTE: this is not super important now that the details can be more thoroughly input with the bigger text field in S@box, but it still renders being able to change the info on asset.party fraught with risk of losing the changes, if you don't remember to make a manual copy of it first.

**Comment by xezno** [comment] 2023-05-17 15:49
Sounds like a duplicate of #3113

**Closed** 2023-05-17 15:49 UTC
Labels: duplicate, feature
