### ISSUE TITLE
Hotload breaks games that use Network

### ISSUE THREAD

**Issue by PolSpock** [sboxgame/issues#4066] opened 2023-09-28 09:01 UTC
### Describe the bug

Hi,

Since a recent update on 27 September 2023 at 10A.M CEST, hotloading a game will create S&box craziness behaviour

It's problematic for developing game

### To Reproduce

I've been able to bring you an easy way to reproduce :
1) Download & mount `sbox-gunfight` https://github.com/Facepunch/sbox-gunfight/
2) Start "FFA - Small Town"
![image](https://github.com/sboxgame/issues/assets/5229571/646618c2-21b6-40f3-8765-e20d12e99bcb)
3) Spawn bots to start game
4) Hotload the game (by editing a file)
5) The game starts to be crazy + if you try to restart `FFA - Small Town` you cannot play anymore with this spamming console error :
```
Could not proxy var 196636 as it does not exist in the network table
   at Sandbox.Internal.VarClass`1.Read(NetRead reader)
   at Sandbox.Internal.Var.Read()
   at Sandbox.NetworkTable.ReadAll(PredictionDataStore prediction)
   at Sandbox.Entity.UpdateFromNetwork()
   at Sandbox.Entity.PredictionStore(Int32 slot, Int32 command_num, Boolean network, Boolean variables)
   at Managed.SourceClient.Exports.Sandbox_Entity_PredictionStore(UInt32 self, Int32 slot, Int32 command, Int32 network, Int32 notnetworked)
   at NativeEngine.EngineGlobal.SourceEngineFrame(CMaterialSystem2AppSystemDict appDict, Double currentTime, Double previousTime)
   at Sandbox.EngineLoop.RunFrame(CMaterialSystem2AppSystemDict appDict, Boolean& wantsQuit)
   at Sandbox.SourceEngineApp.RunFrame() in C:\build\_work\sbox\sbox\engine\Launcher\SourceEngineApp.cs:line 46
   at Sandbox.SourceEngineApp.RunLoop() in C:\build\_work\sbox\sbox\engine\Launcher\SourceEngineApp.cs:line 37
   at Sandbox.Program.LaunchGame() in C:\build\_work\sbox\sbox\engine\Launcher\Launcher.cs:line 108
   at Sandbox.Program.Main() in C:\build\_work\sbox\sbox\engine\Launcher\Launcher.cs:line 58
```

The [sandbox game](https://github.com/Facepunch/sandbox) doesn't have this issue, so i conclude that network replication on hotload is currently broken

### Expected behavior

Hotload must not breaking game

**Comment by Metapyziks** [comment] 2023-09-29 13:00
There were some hotload fixes in the last day or so, can you still reproduce this issue?

**Comment by PolSpock** [comment] 2023-09-29 14:04
I just switched on the stating branch
![image](https://github.com/sboxgame/issues/assets/5229571/6d52bb6e-4569-4b54-b816-7f87c531c9d3)

And still have the same issue
https://github.com/sboxgame/issues/assets/5229571/1974494c-3ab1-4600-9e0f-ccb0ddc85254

**Comment by Metapyziks** [comment] 2023-09-29 14:56
I'll see if I can figure out why it's working on my end then.

**Comment by PolSpock** [comment] 2023-09-29 16:14
I've just have :

1) Desinstalled my s&box, deleting my sbox folder in `Steam\steamapps\common`
Then reinstalled s&box, removed my `-allowlocalhttp -multiple_tools_instances` startup command, switching to `staging` branch
Then launched the S&box for init files. Then closing the game.

2) Downloaded `sbox-gunfight-main`, placed the folder in `Steam\steamapps\common\sbox\addons`
Then launched S&box and mounted `sbox-gunfight`

3) Then restarted S&box in order to correctly load all assets mounted from the added game.
Launched `sbox-gunfight` game, launched `FFA - Small Town` configuration.

4) Hotloaded `GunfightGame.cs` file with a simple CTRL + S without modification with Visual Studio Community
Once again the `sbox-gunfight` game started to be crazy with spamming Prediction errors each tick :
```
 06:05:58  Client [Facepunch.Gunfight.PlayerController] Prediction Error Facepunch.Gunfight.PlayerController.CurrentEyeHeight (3.7333336 (predicted: 64) [tick:4998]
 06:05:58  Client [Facepunch.Gunfight.PlayerController] Prediction Error Facepunch.Gunfight.PlayerController.JumpWinding (True (predicted: False) [tick:4999]
 06:05:58  Client [Facepunch.Gunfight.PlayerController] Prediction Error Facepunch.Gunfight.PlayerController.TimeSinceJumped (169.06668 (predicted: 0) [tick:4999]
```

5) Restarted the game with the blue button
![image](https://github.com/sboxgame/issues/assets/5229571/4403ea3a-8f73-492d-bace-6053f867c167)

6) To be saddened that the issue persists
![image](https://github.com/sboxgame/issues/assets/5229571/b932a7cf-b21a-407d-9f66-5c5b0b723f55)

**Comment by Metapyziks** [comment] 2023-09-29 16:21
I'm getting it now after a full rebuild, not sure what was going on there. Thanks for the repro steps!

**Comment by Metapyziks** [comment] 2023-09-29 22:00
Should be fixed in staging after this builds, please let me know if it's still an issue.

**Closed** 2023-09-29 22:00 UTC
Labels: bug

**Comment by PolSpock** [comment] 2023-09-30 08:24
it's perfect! thx!
Any idea when the `staging` branch is merged to the main branch ?

**Comment by Metapyziks** [comment] 2023-09-30 09:18
Updated the default branch for you now.

**Comment by MrBrax** [comment] 2023-10-07 13:23
This started happening to me again, extreme spam with tens of thousands of could not proxy var logging and concommands that can't be overwritten

**Comment by PolSpock** [comment] 2023-10-08 16:04
> This started happening to me again, extreme spam with tens of thousands of could not proxy var logging and concommands that can't be overwritten.
> 
> Also complete breakage of networking systems and lag after multiple reloads. HUD duplicating over itself. Game menu completely breaking and becoming transparent.

I'm on the 'no beta' branch and i haven't had any problems since the update
Are you using Networable IDictionary which uses BaseNetworkable values? Because I have already made an issue about it https://github.com/sboxgame/issues/issues/2194

I will update this issue in a few days cause is still frustrating for me

**Comment by MrBrax** [comment] 2023-10-08 17:08
Thanks, thought i was going crazy because nobody else was reporting on it.
