### ISSUE TITLE
Ability to draw world panel on front of a view model

### ISSUE THREAD

**Issue by Mbk10201** [sboxgame/issues#3313] opened 2023-05-21 16:34 UTC
### For?

S&Box

### What can't you do?

We can't render a world panel in front of a view model,
I don't know if such feature is possible to be made.

### How would you like it to work?

I don't really know how this can be done, 
but if we can target an entity that will hold the world panel welded to it and the possibility to add the filters things like in sceneobjects.

### What have you tried?

Nothing so far.

**Comment by matekdev** [comment] 2023-05-21 17:55
dupe https://github.com/sboxgame/issues/issues/2285

**Comment by NevaVerse** [comment] 2023-05-21 18:23
I love this idea, genius

**Comment by bakscratch** [comment] 2023-05-21 18:39
dupe of https://github.com/sboxgame/issues/issues/2285

**Closed by bakscratch** 2023-05-21 18:39 UTC
Labels: feature
