### ISSUE TITLE
Intel ARC A770 experiences graphical issues that prevent work.

### ISSUE THREAD

**Issue by Apt-get-CupRamen** [sboxgame/issues#3769] opened 2023-08-01 17:09 UTC
### Describe the bug

Intel Arc A770 (Unverified on the lower end cards) has Graphical issues both in-game and game editor to the point where Hammer is not usable. I believe this is a S&box issue due to other Source 2 games (such as Desk Job and Robot Repair) not having the same graphical issues. 

### To Reproduce

1. Own an Intel Arc A770
2. Set A770 for sbox.exe and sbox-dev.exe
3. Run either the game or Dev tool 

### Expected behavior

The expected results should be garbled shadows and unusable UI in Game Editor  

### Media/Files

All the correct images are from a GT 1030. 
![GT1030hammer](https://github.com/sboxgame/issues/assets/66567490/458bca0c-efcf-414d-bfa5-642fcb48645a)
![GT1030Model](https://github.com/sboxgame/issues/assets/66567490/b7b0f3c0-a875-422e-9e84-d234daaa16cb)
![gt1030ingame](https://github.com/sboxgame/issues/assets/66567490/4ef7e1d3-fe32-4a71-ba75-34d7f6cefa9b)
![A770Ingame](https://github.com/sboxgame/issues/assets/66567490/ebb483f8-77ca-42d5-ab90-53f977ce5faa)
![A770Hammer](https://github.com/sboxgame/issues/assets/66567490/ba8e5266-1856-4e86-9c7f-9205facf57c6)
![A770Model](https://github.com/sboxgame/issues/assets/66567490/c6135caf-f929-4fc4-8187-ce5678e5667c)

### Additional context

I am running Windows 11, 16 GB of RAM, Intel ARC A770 16 GB, GT1030, Ryzen 5 2600.

**Comment by robotboy655** [comment] 2023-08-01 17:56
Duplicate of https://github.com/sboxgame/issues/issues/3051

**Closed by robotboy655** 2023-08-01 17:56 UTC
Labels: bug
