### ISSUE TITLE
Allow users to use Markdown Syntax in their asset descriptions

### ISSUE THREAD

**Issue by DingusPingus** [sboxgame/issues#2917] opened 2023-02-16 03:16 UTC
### For?

Other

### What can't you do?

Currently in a asset description there is almost no customization you can provide in the description, such as changing the font size, **bold**, _italicize_, or even provide [hyperlinks ](https://en.wikipedia.org/wiki/Hyperlink )to other resources.

### How would you like it to work?

I would like more customization in this field so that, for example, people can more easily format a detailed list or provide hyperlinks to perhaps an external wiki they may setup for their game mode or even to social media links. I think a good method to implement these features would be to provide the ability to use Markdown in this description (in the much the same way we can do in GitHub issues right here!).

### What have you tried?

Currently there aren't any work arounds

**Comment by DevulTj** [comment] 2023-02-16 03:26
This is planned.

**Comment by DevulTj** [comment] 2023-02-16 03:28
Oh yeah, duplicate of https://github.com/sboxgame/issues/issues/1113

**Closed by DevulTj** 2023-02-16 03:28 UTC
Labels: feature
