### ISSUE TITLE
LagCompensation pausing

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#3625] opened 2023-07-15 13:20 UTC
### For?

S&Box

### What can't you do?

I can't pause lag compensation while its enabled. Having the ability to do that would make it easier to organize my code.

### How would you like it to work?

If https://github.com/sboxgame/issues/issues/3624 is implemented, it could look something like this:
```cs
using _ = LagCompensation.Enable()

// Later in code

using ( LagCompensation.Pause() )
{
   // Do stuff
}
```

### What have you tried?

Restructuring my code. Not having the ability to pause lag compensation makes it more complex and verbose.

**Comment by xezno** [comment] 2023-07-15 13:22
Duplicate of #3575

**Closed** 2023-07-15 13:22 UTC
Labels: feature request
