### ISSUE TITLE
Map Dynamic Loading

### ISSUE THREAD

**Issue by geferon** [sboxgame/issues#3136] opened 2023-04-13 22:46 UTC
### For?

S&Box, Hammer

### What can't you do?

Ability to be able to dynamically load and unload vmaps, perhaps too with the ability to load multiple instances of one with different offsets and others?
What I'm looking for mainly is something like, random map generation following a set of template rooms that will be connected together.
The main issue I run into with this is the lighting in these rooms and whatnot, I can perfectly export these as models and load them in game, it's just that of course I won't be able to light them properly with compiled lighting, and it would be expensive, although maybe doable.
With the ability to load maps dynamically this would probably be solved in a way?
Although maybe there's a better solution for my problem.

### How would you like it to work?

Some sort of API for loading/unloading maps, or the ability to perhaps, load compiled lighting + meshes at runtime?
List would be more extensive than this probably, unsure of if this would be easy to do or possible at all.

### What have you tried?

Exporting the map as models, exporting an entity list, and loading both. Only issue is no static meshes (it's all props), I loose vis support, and no compiled lighting.

**Comment by GunnarKafel** [comment] 2023-04-14 20:12
Dupe of #2878, this would be really nice to have though!

**Closed** 2023-12-11 23:29 UTC
Labels: feature request
