### ISSUE TITLE
css :outro property not deleting element in certain situations

### ISSUE THREAD

**Issue by kodi022** [sboxgame/issues#3874] opened 2023-08-19 05:26 UTC
### Describe the bug

Weird to explain, from what i can tell

delete an element, have it outro
access the element again during the outro, or maybe get it to intro during it??
it will freeze at that point in the outro until not accessed again i think

It's actively happening on sandtycoon right now
The tycoon iterates though Children.OfType<> to find the floating texts, then those are messed with if their target button is in range, i can only guess that by leaving the range which calls .Delete on that text, starting the outro, and entering the range again before outro finishes it accesses the element and stops the outro, making it not fully delete

### To Reproduce

1. open sandtycoon in editor
2. in editor go to UI Panels => editedrootpanel => floatingtext
3. go near a button, 'floattext' s will show up
4. leave the buttons floattext range and quickly reenter before the outro ends (like half a second window or something)
5. the floattext will be stuck in the outro or something, im not sure
6. leaving the radius for longer will either start the outro again or finish it, deleting the floattext correctly
7. entering again makes them appear correctly

### Expected behavior

outro should not be halted under any circumstances, they should fully delete instead of being in outro limbo

### Additional context

this didnt happen just 1 or a few weeks ago

**Comment by xezno** [comment] 2023-09-01 13:28
Duplicate of #2569

**Closed by xezno** 2023-09-01 13:28 UTC
Labels: bug
