### ISSUE TITLE
LocalAttribute not functioning properly

### ISSUE THREAD

**Issue by yikegaming** [sboxgame/issues#2721] opened 2022-12-31 02:47 UTC
### Describe the bug

When trying to make a NetworkAttribute Local, it still sends to every client, not just the owner of the attribute.

### To Reproduce

Add a [Net, Local] to a variable on the player and create a server command to change said variable on the caller player. Have a friend come on and open the entity viewer. Now use the command to change the variable on the server and have your friend tell you what the value changed to in their entity viewer, it also changed, which shouldn't happen. Like this:

```
[Net, Local]
public int testNum {get; set;} = 0;

[ConCmd.Server( "changenum" )]
public static void test()
{
var target = ConsoleSystem.Caller.Pawn as Player;
target.testNum = 5;
}
```

### Expected behavior

The networked variable should only be sent to the entities client, as described [here](https://asset.party/api/Sandbox.LocalAttribute)

**Comment by DrewBritt** [comment] 2022-12-31 06:17
Dupe of #2169. DevulTJ has noted on Discord several times that it's simply not hooked up to anything yet, I'm sure it'll be taken care of sometime before launch :)

**Closed** 2023-01-01 16:04 UTC
Labels: bug
