### ISSUE TITLE
Can't ever build project solution in Visual Studio Community. `MSB4018	The "ResolvePackageAssets" task failed unexpectedly.`

### ISSUE THREAD

**Issue by Jac0xb** [sboxgame/issues#872] opened 2021-09-06 04:29 UTC
**Describe the bug**

In any of my projects I cannot debug or build the current project because of `MSB4018	The "ResolvePackageAssets" task failed unexpectedly.`

![image](https://user-images.githubusercontent.com/5273873/132160573-024cfb40-a454-49ed-bca4-6790a800c23d.png)

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "ResolvePackageAssets" task failed unexpectedly.
NuGet.Packaging.Core.PackagingException: Unable to find fallback package folder 'C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages'.
   at NuGet.Packaging.FallbackPackagePathResolver..ctor(String userPackageFolder, IEnumerable`1 fallbackPackageFolders)
   at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver(IEnumerable`1 packageFolders)
   at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver(LockFile lockFile)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	grandprix	C:\Program Files\dotnet\sdk\5.0.301\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	241	
```

**To Reproduce**

Open visual studio code sandbox project. Run debugger, get build errors and never able to run debugger on latest compiled version.

**Expected behavior**

**Screenshots**

**Additional context**

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.

**Comment by xezno** [comment] 2023-07-19 13:22
Closing this because it's old, I can't reproduce it, and it looks to me like a Visual Studio error

**Closed by xezno** 2023-07-19 13:22 UTC
Labels: bug
