### ISSUE TITLE
Custom Grid size and Snapping Angle for Hammer Editor

### ISSUE THREAD

**Issue by Baik90** [sboxgame/issues#2677] opened 2022-12-12 17:59 UTC
### For?

Hammer

### What can't you do?

I'm unable to set the Hammer Grid size or Snapping Angle to a Custom value, only to a Fixed One.

### How would you like it to work?

![grafik](https://user-images.githubusercontent.com/88790023/207117287-5b621b79-ef6e-49f5-b8de-d42007a5caf5.png)
You should be able to just click in the dropdown to change the numbers, even if the numbers are odd or decimal.

### What have you tried?

Use the Transformation tab in the Object Properties.

### Additional context

It would be a "Nice to Have" feature.

**Comment by robotboy655** [comment] 2022-12-12 18:05
Duplicate of https://github.com/sboxgame/issues/issues/924

**Closed by robotboy655** 2022-12-12 18:05 UTC
Labels: feature, 🗺 Hammer
