### ISSUE TITLE
Light curve animation should not be internal

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#3059] opened 2023-03-24 06:09 UTC
### What it is?

The animation curve use for the brightness multiplier animation

### What should it be?

It should not be internal and should be made either private or public so that we are able to set animation on lights in code using the new curves

**Comment by robotboy655** [comment] 2023-03-24 15:25
Basically duplicate of https://github.com/sboxgame/issues/issues/3053

**Closed by robotboy655** 2023-03-24 15:25 UTC
Labels: api design
