### ISSUE TITLE
Change EntityComponent generic constraint to IEntity interface

### ISSUE THREAD

**Issue by peter-r-g** [sboxgame/issues#3109] opened 2023-04-07 17:55 UTC
### What it is?

Currently, the `EntityComponent` generic constraint limits you to a class type of `Entity`.

### What should it be?

It should instead be limited to a type that implements the `IEntity` interface. This way you can use classes that implement `IEntity` and you can use interfaces that derive from `IEntity`. This would be useful in cases where you have entities with different bases but implement similar functionality.

**Comment by LeQuackers** [comment] 2023-04-07 18:35
I think this is already planned in the next pain day #2858

**Comment by DevulTj** [comment] 2023-04-10 23:31
Duplicate of https://github.com/sboxgame/issues/issues/2858

**Closed by DevulTj** 2023-04-10 23:31 UTC
Labels: api design
