### ISSUE TITLE
[Hammer] Asset Picker breaks Object Properties

### ISSUE THREAD

**Issue by SharpMars** [sboxgame/issues#2653] opened 2022-12-07 17:11 UTC
### Describe the bug

When using asset picker for e.g. when choosing Sky Material, it breaks the Object Properties window after reopening it. It mainly breaks the properties list in it. It throws a lot of QT warnings.

### To Reproduce

1. Open Object Properties for entity with selectable asset e.g. env_sky
2. Open the asset picker
3. Choose an asset
4. Close Object Properties
5. Reopen it
6. See the issue

### Expected behavior

This shouldn't happen.

### Media/Files

https://user-images.githubusercontent.com/70289680/206244430-e685d178-804b-49a3-9cbd-99d6104f506d.mp4

[Log.log](https://github.com/sboxgame/issues/files/10178311/Log.log)

**Comment by robotboy655** [comment] 2022-12-07 18:01
Duplicate of https://github.com/sboxgame/issues/issues/2510

**Closed by robotboy655** 2022-12-07 18:01 UTC
Labels: bug, duplicate, 🗺 Hammer, tools
