### ISSUE TITLE
Can no longer Select Local maps, Local map button wont appear in map-change menu

### ISSUE THREAD

**Issue by codecakegit** [sboxgame/issues#3200] opened 2023-04-25 05:20 UTC
### Describe the bug

24 hours ago I had things setup with Launch Config, I press play and it opens a local gamemode and a local map. Today I can no longer  find the map in the Launch Config menu and When I click into one of my local gamemode lobbys and go to change map the Local button is no longer there so it's impossible for me to select my local map even though the addon manager has it included.

### To Reproduce

1. Go to Games menu
2. Select a Local Gamemode
3. Create Game
4. Click to Change map
5. You will not be able to find your local map, Local Map button is gone.

### Expected behavior

I should be able to play a local gamemode with a local map if everything is added to addon-manager correctly.

### Media/Files

![alocalmapoption](https://user-images.githubusercontent.com/91923054/234181028-385ac724-c2b7-49cd-90ae-0885b4b58fae.png)

![findlocal](https://user-images.githubusercontent.com/91923054/234181246-6a1af9c6-49b1-4108-b08c-44fada1d6639.PNG)

### Additional context

I asked a few people in the discord and they confirmed it's missing for them also.

**Comment by robotboy655** [comment] 2023-04-25 14:32
Basically duplicate of https://github.com/sboxgame/issues/issues/1555

**Comment by DoctorGurke** [comment] 2023-04-25 14:36
This worked until last week though

**Comment by robotboy655** [comment] 2023-04-25 15:00
Yeah, it was looking for local projects of type "map" which no longer exist. It should be looking for individual files now, which is also what is necessary to solve #1555

**Closed** 2023-05-03 02:55 UTC
Labels: bug
