### ISSUE TITLE
Tools: MenuBar Menu Options don't size properly with icons involved

### ISSUE THREAD

**Issue by DoctorGurke** [sboxgame/issues#1829] opened 2022-05-13 16:45 UTC
### Describe the bug

Using icons on some menu bar options but not others will seemingly not account properly for the icon offset on options without icons. This will lead to improper sizing when an option without an icon has an overall longer label.

### To Reproduce

Use the code below to make a simple test window with some MenuBar items.

```csharp
using Tools;

public class TestWindow : Window
{
	public TestWindow()
	{
		// init window
		Size = new( 500, 500 );

		// init MenuBar
		var menu = MenuBar.AddMenu( "Test" );
		menu.AddOption( "Short", "map" );
		menu.AddOption( "Long Option Name" );
		menu.AddOption( "Short", "map" ); 

		Show();
	}

	[Menu( "Editor", "Test Window/Open Menu Test Window" )]
	public static void ExampleMenuOption()
	{
		_ = new TestWindow();
	}
}
```

### Expected behavior

The MenuBar sub menu should size properly based on all its elements.

### Media/Files

![sbox-dev_lvT3coTlHS](https://user-images.githubusercontent.com/12602100/168329463-02e1848a-98de-4837-874a-46d7eaebbc9e.png)

**Comment by xezno** [comment] 2023-04-18 10:55
I think this was fixed a while ago - I can't reproduce this anywhere. Gonna close it, feel free to re-open it if you find it's still a problem.

![image](https://user-images.githubusercontent.com/12881812/232756216-d0ec88af-7352-4241-b544-a333d9eb8378.png)

**Closed by xezno** 2023-04-18 10:55 UTC
Labels: bug, tools
