### ISSUE TITLE
Can't load local maps without creating a separate addon for it

### ISSUE THREAD

**Issue by gvarados1** [sboxgame/issues#1627] opened 2022-02-18 01:02 UTC
**Describe the bug**
We can't load maps without creating a separate addon for it.

We can load the map manually through the console. It kicks you back to the menu if you try loading through hammer or the game creation menu.

**To Reproduce**
1. Create a map, not in it's own unique addon.
2. Try to play the map in-game, by starting a game or after compiling in hammer.
3. See error

**Expected behavior**
All local maps should load.

**Comment by gvarados1** [comment] 2022-02-18 03:34
Looks like starting maps through hammer was fixed. We still need to be able to see all maps in the menu though.

**Comment by robotboy655** [comment] 2022-02-18 20:10
I am 99% sure maps not appearing in map selection is exactly the same issue as https://github.com/Facepunch/sbox-issues/issues/1565

**Comment by robotboy655** [comment] 2023-04-21 14:51
I think this can be marked as a duplicate of https://github.com/sboxgame/issues/issues/1555

**Closed by robotboy655** 2023-04-21 14:51 UTC
Labels: bug
