### ISSUE TITLE
GameResource Properties Revert to default 

### ISSUE THREAD

**Issue by TheBoxTrot** [sboxgame/issues#2918] opened 2023-02-16 05:27 UTC
### For?

S&Box

### What can't you do?

we are able to set a default value for properties but if you change it you can't revert it to default only clear it

### How would you like it to work?

when right-clicking if the property has a default value have an extra option to revert to default

### What have you tried?

NA

**Comment by Fortune117** [comment] 2023-02-16 05:33
seems like a dupe of #2915

**Closed** 2023-02-16 14:25 UTC
Labels: feature
