### ISSUE TITLE
Images appearing glitchy/corrupted on AMD

### ISSUE THREAD

**Issue by maxjaudio** [sboxgame/issues#3347] opened 2023-05-29 04:21 UTC
### Describe the bug

When I open s&box and any of the contained gamemodes, most sprites/menu icons appear "glitchy" or "corrupted". Note: I have verified my game files via Steam.

### To Reproduce

1. Open s&box.

### Expected behavior

The expected result would be sprites appearing as they were created.

### Media/Files

![image](https://github.com/sboxgame/issues/assets/31394147/835c3e06-8736-495f-84dc-b3bc61ee35d5)

![image](https://github.com/sboxgame/issues/assets/31394147/ff120865-a0f7-495f-a1a5-1f1d60e53592)

![image](https://github.com/sboxgame/issues/assets/31394147/07dd3076-4be5-4486-abe3-0d9aa0227092)

### Additional context

I'm running Windows 10, GPU is RX 6650-XT.

**Comment by Gun-Done** [comment] 2023-06-11 07:38
Same, win 10, rx 6650 xt

**Comment by MishaMykha** [comment] 2023-06-30 22:50
Same issue, happens on reference RX 6750 XT with 23.5.2 drivers installed on Windows 11 (build 22621.1928)

**Comment by R4to0** [comment] 2023-07-01 03:53
Same issue here. RX 6600 with latest drivers (currently at 23.5.2) on Windows 11. The issue goes away when running with vulkan but it crashes after a while (different issue I believe).

**Comment by AlexBaker2648** [comment] 2023-07-02 16:53
Same issue, i have an RX 6700 (non xt) with 23.5.2 installed on Windows 10 22H2, OS Build: 19045.3086

**Comment by gidgeesheep** [comment] 2023-07-04 21:45
Going to dump a list of observations in the hopes of helping out.

### S&box Image Glitch Patterns and Observations

1. Static Images are affected in UI interfaces.

2. Preloaded videos do not seem to be affected.

https://github.com/sboxgame/issues/assets/55063683/ce2c82c3-e429-4a01-b432-262db324080b


3. The intensity is affected by the size of the image. If the image is small, the issue is more intense. Full scale images don't look to be affected.

<img width="1280" alt="Screenshot 2023-06-30 200209" src="https://github.com/sboxgame/issues/assets/55063683/51d2f544-cba2-47e2-9856-d6e658f4f340">

Screenshot previews enlarged

<img width="1280" alt="Screenshot 2023-06-30 200219" src="https://github.com/sboxgame/issues/assets/55063683/e018844a-914e-439b-9fda-ee3759f73250">
<img width="1280" alt="Screenshot 2023-06-30 200224" src="https://github.com/sboxgame/issues/assets/55063683/b7c370d1-a0e0-4bd7-938f-af8d71eab0bf">


4. Rendered avatar clothes buttons have a special case. The artifacts are lowered in opacity when the anisotropic filtering is set to x16. I can't see this anywhere else.

<img width="1280" alt="Screenshot 2023-06-30 201624" src="https://github.com/sboxgame/issues/assets/55063683/bfbf80f5-bfc4-4129-838c-fcbb5c6fb31b">
<img width="1280" alt="Screenshot 2023-06-30 201613" src="https://github.com/sboxgame/issues/assets/55063683/82df426e-e581-45f5-974c-c01c615c9b97">


5. Menu pictures in sandbox Dev are not affected, only within game.

<img width="1280" alt="Screenshot 2023-07-04 171600" src="https://github.com/sboxgame/issues/assets/55063683/c4dd3b03-3867-47ff-8530-2ba0300ab171">

6. The glitch is not affected by window size, only when the image scale changes.

<img width="1280" alt="Screenshot 2023-06-30 203356" src="https://github.com/sboxgame/issues/assets/55063683/41358488-3b45-4abb-ac9d-d0f2160ff802">
<img width="1280" alt="Screenshot 2023-06-30 203420" src="https://github.com/sboxgame/issues/assets/55063683/8de7128e-90de-4ada-8b86-a1391bcc81ae">


7. The steam profile picture isn't affected, whether static or animated.

<img width="276" alt="Screenshot 2023-06-30 201648 closeup" src="https://github.com/sboxgame/issues/assets/55063683/009d82bd-2255-4761-8884-41efe5ade255">

8. Organization profile images are affected.

9. The graphic glitch does not appear to happen when using a different GPU on the same system, such as when windows uses the low power GPU on a laptop.
	
There is no error running on this GPU (https://www.techpowerup.com/gpu-specs/radeon-graphics-512sp-mobile.c3771)
	
<img width="1280" alt="Screenshot 2023-07-04 171844" src="https://github.com/sboxgame/issues/assets/55063683/6416d431-e5f3-4d16-af2e-6ec38147f5e9">

This GPU produces the error (https://www.techpowerup.com/gpu-specs/radeon-rx-6800m.c3786)

<img width="1280" alt="Screenshot 2023-07-04 172022" src="https://github.com/sboxgame/issues/assets/55063683/649edf1b-f022-4cc6-a06e-601fad7e6f17">


10. UI elements aren't affected. Vector graphics are not affected. Text is not affected.

11. Games can be affected if they  use static images.

<img width="1280" alt="Screenshot 2023-07-04 173951" src="https://github.com/sboxgame/issues/assets/55063683/81577dce-2581-4bc4-98dd-e10fbb0c8c3d">
<img width="1280" alt="Screenshot 2023-07-04 174009" src="https://github.com/sboxgame/issues/assets/55063683/a84c3218-fba2-4f22-a699-a448f3e65ac5">
<img width="1280" alt="Screenshot 2023-07-04 174108" src="https://github.com/sboxgame/issues/assets/55063683/9ad4ae41-1b3f-4c21-819b-c267ce48f72b">

**Comment by aylaylay** [comment] 2023-07-05 02:06
This should be fixed now. Thanks for the breakdown @gidgeesheep it helped me narrow down where to look.

**Comment by gidgeesheep** [comment] 2023-07-05 02:10
Oh yeah this is all fixed for me 🤩

**Comment by popyop45** [comment] 2023-07-05 02:32
The Fix seems to have worked for me, Everything is back to normal now, thanks for the fix

**Comment by R4to0** [comment] 2023-07-05 04:24
Can confirm the fix works. Thanks a lot for the fix!

![image](https://github.com/sboxgame/issues/assets/3608184/4c8b5c10-cb73-47a7-b301-4c8be37febdd)

**Comment by Gun-Done** [comment] 2023-07-05 08:33
for sure

![image](https://github.com/sboxgame/issues/assets/72692514/a679da6b-c765-4260-92a4-4a319b8ffb26)

**Comment by scorteanucosmin** [comment] 2023-07-05 09:30
The update fixes the issue for my 6900 XT as well

**Closed** 2023-07-05 09:57 UTC
Labels: bug, review
