### ISSUE TITLE
Game.Server.RequiredContent might be inconsistent.

### ISSUE THREAD

**Issue by Thomas-Lazenby** [sboxgame/issues#3206] opened 2023-04-26 18:21 UTC
### Describe the bug

When you look at both client and server Requiredcontent, on client it has the map in it and on server it doesnt have anything. I would expect if you mount it would be on the list as requiredcontent as when you join your download any packages on the "server" and can see that doing package_list.

Just to add, any packages also mounted aren't added to that list.

### To Reproduce

You can print it.

### Expected behavior

I expect it to mount that or a variable that gives data such as package_list. But I aint sure overall, if it should be a different variable etc.

**Comment by cr4yz** [comment] 2023-05-02 16:28
This should be fixed in the next build

**Comment by DevulTj** [comment] 2023-05-20 00:15
ServerInformation (Game.Server) is sent when you connect only, it's by design that it doesn't change

**Closed** 2023-11-11 04:20 UTC
Labels: bug
