### ISSUE TITLE
Code editor keeps s&box running on Steam

### ISSUE THREAD

**Issue by Weldify** [sboxgame/issues#2558] opened 2022-11-17 20:38 UTC
### Describe the bug

Opening your solution and closing (or crashing) S&box makes Steam think it's still running until you close the code editor

### To Reproduce

1. File -> Open Solution (Ctrl+P)
2. Close S&box

Steam won't let you start S&box until you close your code editor

### Expected behavior

You shouldn't have to close your code editor for Steam to see you're no longer in S&box

### Additional context

Windows 11,
Tested with VS and VSCode, bug occurs on both

**Comment by ogniK5377** [comment] 2022-11-24 00:16
I am unable to reproduce this, i've tried using Visual Studio, VS Code, on windows 11, tried with administrator access & without, launching from the games directory as well as from steam, tried using the dev build as well as exiting the game multiple ways. Is there anything else you could be doing differently?

**Comment by Weldify** [comment] 2022-11-24 00:31
I've switched back to Windows 10 a couple days back, but the issue still persists. No matter whether I open S&box dev through the app or through steams prompt by pressing play. It doesn't need admin rights, and it doesn't matter if I do ctrl+P or right click my game and click open

**Comment by trundler-dev** [comment] 2022-11-24 00:35
This happens to me too. Windows 10. I launch sbox-dev.exe as a game on Steam, and Ctrl+P to open Visual Studio. I don't think it happens consistently.

**Comment by lotuspar** [comment] 2022-11-25 10:53
Just reproduced (on accident):

1. open s&box editor
2. right click on a gamemode & click "Open in Rider" or whatever you use
3. close the s&box editor

It stays open in steam and clicking Stop closes Rider too

**Comment by garrynewman** [comment] 2022-11-25 11:55
This is a steam thing. It's unavoidable afaik. It thinks the game is running because an exe it spawned is running.

**Comment by edisonlee55** [comment] 2022-12-05 10:13
This bug can be reproduced when closing the s&box editor without first closing the IDE that is spawned by s&box.
In my case, it is even more annoying. Clicking "Stop" in Steam can't stop the game (both s&box and IDE are already closed, but Steam just failed to detect them.)
Therefore, I must restart Steam completely if I want to launch s&box again.

As Garry said, it is a steam thing. (Valve pls fix.)
But maybe the s&box editor can implement a kindly warning when the user tries to close the editor without closing IDE spawned by s&box first.

**Comment by SplatzyXD** [comment] 2023-03-15 19:37
Alt f4 out of sbox and easy LMAO

**Comment by SplatzyXD** [comment] 2023-03-15 19:37
litteraly will keep the IDE open as it was still running sbox

**Closed** 2023-03-16 09:23 UTC
Labels: bug
