### ISSUE TITLE
Map downloads aren't stopped when download is cancelled

### ISSUE THREAD

**Issue by Ryhon0** [sboxgame/issues#3677] opened 2023-07-20 22:11 UTC
### Describe the bug

When you press the cancel button during a map download, the map download is not stopped.
This also causes flickering text when downloading another map or loading an already downloaded map.

### To Reproduce

* Select any game
* Select a map which hasn't been downloaded yet
* Start the game
* Press the cancel button
* Select another map
* Start the game again

### Expected behavior

The download of the map is stopped when the cancel button is pressed

**Comment by DevulTj** [comment] 2023-07-24 14:41
linking as duplicate of internal issue https://github.com/Facepunch/sbox/issues/1184

**Comment by DevulTj** [comment] 2023-07-25 13:28
This should now be resolved

**Closed** 2023-08-16 18:38 UTC
Labels: bug, review
