### ISSUE TITLE
[Hammer] Quad Slice tool works kinda weird.

### ISSUE THREAD

**Issue by FullStack0verfl0w** [sboxgame/issues#716] opened 2021-08-18 13:36 UTC
**Describe the bug**
I want to slice two neighbor faces using "Quad Slice" tool. But it only slices one face, and slicing the second face does nothing.

**To Reproduce**
1. Create a cube.
2. Select front and top faces.
3. Try to slice them using "Quad Slice"

**Expected behavior**
All selected faces should be sliced.

**Screenshots**
[Video](https://www.youtube.com/watch?v=NuJluC7HelM)

**Additional context**
I know I can split common edge and slice faces, but I still have to merge new edges, and when there are a lot of them it gets really annoying.

**Comment by robotboy655** [comment] 2021-09-20 14:05
The issue is that when a face is subdivided it makes certain adjacent faces non quads (since new vertices were added to them), so the algorithm cannot subdivide those faces that are no longer quads.

This unfortunately cannot be fixed without changing the algorithm to something that can handle non quads.

**Comment by aylaylay** [comment] 2021-12-14 13:12
Should be fixed now

**Comment by pBinarySoul** [comment] 2021-12-14 13:59
> Should be fixed now

It works here just fine
![image](https://user-images.githubusercontent.com/36414434/146011961-0bedbf01-264b-4455-a4a7-92be5cfa1b6a.png)

But not here
![image](https://user-images.githubusercontent.com/36414434/146012312-f47e3070-c322-4e3f-8238-c09008b8aa5e.png)

Anyway it's better than it was before.

**Closed** 2023-09-18 17:21 UTC
Labels: bug, tool:hammer
