### ISSUE TITLE
TypeLibrary doesn't work on tuples

### ISSUE THREAD

**Issue by lotuspar** [sboxgame/issues#3228] opened 2023-05-01 17:37 UTC
### Describe the bug

TypeLibrary.GetType returns null on tuples

I'm trying to get the generic arguments of a tuple - TypeLibrary doesn't work and Type.GenericTypeArguments isn't in the whitelist

### To Reproduce

```cs
var tuple = (3, 3);
Log.Info( TypeLibrary.GetType( tuple.GetType() ) );
```

### Expected behavior

The description gets returned

**Comment by robotboy655** [comment] 2023-05-01 19:13
I think this is basically a duplicate of https://github.com/sboxgame/issues/issues/2550

**Closed** 2023-06-07 18:46 UTC
Labels: bug
