### ISSUE TITLE
Lags in (Construct) Map

### ISSUE THREAD

**Issue by Fedox-die-Ente** [sboxgame/issues#3329] opened 2023-05-24 23:48 UTC
### Describe the bug

When I go to the Construct map in Sandbox I have extreme FPS problems with 10 FPS I run around there, the error also occurs only on the map, otherwise on no other.

PS:

If I look in a corner the FPS are more again as you can see in the picture, it will be towards the water/warehouse.
![image](https://github.com/sboxgame/issues/assets/67076970/221b4020-a04f-42ea-9bf4-494dea8f6953)

### To Reproduce

1. Go on sandbox
2. Select construct map
3. have fun

### Expected behavior

I think no lags

### Media/Files

![image](https://github.com/sboxgame/issues/assets/67076970/6b900c51-5a9f-48ad-b786-7875bd98e94b)

### Additional context

Im running on windows 10.
My computer specs:

GeForce RTX 3050
Intel Core i7-6700 3,40GHz
32GB Ram

**Comment by xezno** [comment] 2023-06-08 13:52
Duplicate of #1577

**Closed by xezno** 2023-06-08 13:52 UTC
Labels: bug
